services:
  frontend:
    build: ./shms-frontend
    container_name: angular-app
    ports:
      - "4200:80" # Map port 4200 on the host to port 80 in the container
    volumes:
      - /app/node_modules # Cache dependencies
    restart: always
    environment:
      - STYLE=scss
  backend:
    build: ./shms-backend
    container_name: "shms-spring-boot"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shmsdatabase
      - SPRING_DATASOURCE_USERNAME=shmsuser
      - SPRING_DATASOURCE_PASSWORD=SHMSuserhasverystrongpassword
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
  mysql:
    container_name: "shms-mysql"
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=shmsdatabase"
      - "MYSQL_PASSWORD=SHMSuserhasverystrongpassword"
      - "MYSQL_ROOT_PASSWORD=SHMShastheunbreakablepassword"
      - "MYSQL_USER=shmsuser"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
